apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: actions-aks-app
spec:
  replicas: 3
  template:
    metadata:
      name: ng-pod
      labels:
        target: ng-pod
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: nginx
        image: vittorioacr.azurecr.io/actionsaksk8sdemo:___IMAGE_VERSION___
        resources: 
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 80
          protocol: TCP