name: Build and publish image acr

on:
  push:
    branches:
      - feature/*
    paths:
      - src/**
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOURCE_DATA: ${{ github.workspace }}/src
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Package binaries
        uses: actions/upload-artifact@v1
        with:
          name: image-source
          path: ${{ env.SOURCE_DATA }}
    

  publish-acr:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      IMAGE_FOLDER: ${{ github.workspace }}/image
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4.1.7
        with:
          name: image-source
          path: ${{ env.IMAGE_FOLDER }}
      
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.VITTORIO_AZURE_CREDENTIALS }}

      - uses: Azure/get-keyvault-secrets@v1.0
        with:
          keyvault: "vittorio-kv"
          secrets: 'acr-username, acr-password'
        id: mySecrets
      
      - uses: Azure/docker-login@v1
        with:
          login-server: vittorioacr.azurecr.io
          username: ${{ steps.mySecrets.outputs.acr-username }}
          password: ${{ steps.mySecrets.outputs.acr-password }}
      
      - run: |
          docker build -t vittorioacr.azurecr.io/actionsaksk8sdemo:${{ github.sha }} ${{ env.IMAGE_FOLDER }}
          docker push vittorioacr.azurecr.io/actionsaksk8sdemo:${{ github.sha }}